#!/usr/bin/env zsh
# Fuzzy cloner of GitHub repos.
# author: https://github.com/samedamci

local user=${1:-$USER}
local data=$(curl -s -n "https://api.github.com/users/$user/repos?per_page=100&page=1")

if [[ $data =~ "Not Found" ]]; then
  echo "[E] Incorrect user."
  return 1
fi

local repos=$(jq --stream -r 'select(.[0][1] == "full_name") | .[1]' <<<$data)

[[ -z $repos ]] && {
  echo "This user don't have any public repo!"
  return 1
}

fzf --reverse --height=40% \
  --bind "enter:execute(git clone git@github.com:{})" \
  --bind "ctrl-h:execute(git clone https://github.com/{})" \
  --bind "ctrl-b:execute($BROWSER https://github.com/{})" <<<$repos
