#!/usr/bin/env zsh
# Generate directories / files shortcuts.
local shortcutrc=$ZDOTDIR/shortcutrc
{
  print "# vim: filetype=sh"

  # named directories
  while read -r name dest; do
    print "hash -d $name=$dest"
  done <~/.config/zsh/directories

  # directories bookmarks
  while read -r name dest; do
    print "alias $name=\"cd $dest && ls -a\""
  done <~/.config/zsh/directories

  # files bookmarks
  while read -r name dest; do
    print "alias $name=\"$EDITOR $dest\""
  done <~/.config/zsh/files
} >$shortcutrc
