#!/usr/bin/env zsh
# Simple http python3 server for files or pages.

local port=8080
local ip=$(ip addr show wlan0 | grep -oP "\d*\.\d*\.\d*\.\d*" | head -1)
local pidfile=/tmp/simple-server.pid
local logfile=/tmp/simple-server.log

while getopts ':p:sblh' opt; do
  case $opt in
    p) port=$OPTARG;;
    s) if [[ ! -e $pidfile ]]; then
         echo "server not started"
         return
       fi
       kill -9 $(<$pidfile) &>/dev/null
       =rm $pidfile
       print "server terminated"
       return;;
    b) local run_browser=1;;
    l) less $logfile; return;;
    h) cat <<-EOF >&2
Usage: $0 [-option] [directory]

Options:
  -p port   Port on which run server
  -b        Open in browser
  -l        Show log
  -h        Help
EOF
       return;;
    \?) echo "invalid option: -$OPTARG" 1>&2; return 1;;
    :)  echo "invalid option: -$OPTARG requires an argument" 1>&2; return 1;;
  esac
done
shift $((OPTIND - 1))

if [[ ! -e $pidfile ]]; then
  nohup python3 -u -m http.server --bind $ip --directory ${1:-$PWD} $port &>$logfile &
  print $! >$pidfile
  if [[ -n $run_browser && -n $BROWSER ]]; then
    $BROWSER "http://${ip}:${port}"
  fi
else
  echo "serv already running"
fi
