#!/usr/bin/env zsh
#                           ██            ████
#                          ░░            ░██░
#   ██████  ██   ██  ██████ ██ ███████  ██████  ██████
#  ██░░░░  ░░██ ██  ██░░░░ ░██░░██░░░██░░░██░  ██░░░░██
# ░░█████   ░░███  ░░█████ ░██ ░██  ░██  ░██  ░██   ░██
#  ░░░░░██   ░██    ░░░░░██░██ ░██  ░██  ░██  ░██   ░██
#  ██████    ██     ██████ ░██ ███  ░██  ░██  ░░██████
# ░░░░░░   ██      ░░░░░░  ░░ ░░░   ░░   ░░    ░░░░░░
#        ░░
#
#█▓▒░ vars
#local full=▓
#local empty=░
local full=━
#local empty=━
#local empty=─
#local full=┅
local empty=┄

local distro='Arch Linux'
local kernel="$(uname -r)"
local pkgs="$(pacman -Qqs | wc -l)"
local wm="$(awk '/^exec/ { print $2 }' ~/.xinitrc)"
local font='Hack Nerd Font'
local colors='icebergs'

#█▓▒░ progress bar
function draw_bar() {
  local perc=$1
  local size=$2
  local length=$((perc * size / 100))
  local color=${3-36}
  for (( i=0; i <= 10; i++ )); do
    if (( $i <= $length )); then
      print -Pn "\e[1;${color}m${full}"
    else
      print -Pn "\e[0;${color}m${empty}"
    fi
  done
}

#█▓▒░ colors
print
for (( i=0; i <= 6; i++ )); do
  print -n "\e[$((i + 41));$((i + 30))m█▓▒░"
done
print "\e[37m█\e[0m▒░\n"

#█▓▒░ greets
print " \e[0m  hello \e[36m$USER\e[0m, i'm \e[34m$HOST\e[0m\n"

#█▓▒░ environment
print " \e[1;33m      distro \e[0m$distro"
print " \e[1;33m      kernel \e[0m$kernel"
print " \e[1;33m    packages \e[0m$pkgs"
print " \e[1;33m          wm \e[0m$wm"
print " \e[1;33m        font \e[0m$font"
print " \e[1;33m      colors \e[0m$colors\n"

#█▓▒░ cpu
local cpu=$(awk '/cpu/ {usage=($2+$4)*100/($2+$4+$5)} END {print int(usage)}' /proc/stat)
print -f "    \e[0;36m cpu \e[1;36m%-5s %s\n" $cpu% $(draw_bar $cpu 10)

#█▓▒░ ram
local ram=$(free | awk '/Mem:/ {print int($3/$2 * 100.0)}')
print -f "    \e[0;36m ram \e[1;36m%-5s %s\n" $ram% $(draw_bar $ram 10)

#█▓▒░ battery
local battery=(/sys/class/power_supply/BAT?)
local charge=$((100 * $(<$battery/charge_now) / $(<$battery/charge_full)))
(( $charge <= 20 )) && color=31 || color=36
print -f "    \e[0;${color}m bat \e[1;${color}m%-5s %s\n" $charge% $(draw_bar $charge 10 $color)

#█▓▒░ volume
local vol=$(amixer get Master | awk -F"[][%]" '$0~/%/ { print $2; exit }')
[[ "$(amixer get Master)" =~ off ]] && color=31 || color=36
print -f "    \e[0;${color}m vol \e[1;${color}m%-5s %s\n" $vol% $(draw_bar $vol 10 $color)

#█▓▒░ temperature
local temp=$(sensors | awk '/Core 0/ {gsub(/\+/,"",$3); gsub(/\..+/,"",$3); print $3}')
(( $temp >= 70 )) && color=31 || color=36
print -f "    \e[0;${color}mtemp \e[1;${color}m%-5s %s\n" $temp°C $(draw_bar $temp 15 $color)
