#!/usr/bin/env zsh
# Generate colors for tty from X server resource databas
local file='/usr/local/bin/ttycol.sh'
local serv='/usr/lib/systemd/system/ttycol.service'
local col=($(xrdb -query | sed -rn 's/\*.?color//gp' | sort -n | cut -d'#' -f2))
local col[1]=$(xrdb -query | awk -F "#" '/\*.?background:/ { print $2 }')
{
  print '#!/usr/bin/env zsh'
  print 'for tty in /dev/tty[0-9]; do'
  print '\t[ -w $tty ] || continue'
  for (( i=0; i<16; i++ )); do
    [[ $i < 10 ]] && fmt='%s' || fmt='%X'
    print -f '\tprint "\\e]P'$fmt'%s" > $tty\n' $i $col[$((i + 1))]
  done
  print 'done'
} | sudo tee >$file; chmod +x $file
[ -e $serv ] || cat << EOF | sudo tee $serv >/dev/null
[Unit]
Description=Change tty colours
After=multi-user.target
[Service]
Type=oneshot
ExecStart=$file
[Install]
WantedBy=multi-user.target
EOF
