#!/usr/bin/env zsh
# Generate colors for tty from X server resource databas
colours=($(xrdb -query | sed -n 's/*.color//gp' | sort -n | awk -F '#' '{ print $2 }'))
colours[1]=$(xrdb -query | awk -F "#" '/\*.background/ { print $2 }')
{
  cat <<EOF
#!/usr/bin/env zsh
for tty in /dev/tty[0-9]; do
EOF

  for (( i=1; i<=$#colours; i++ )); do
    case $i in
    11) n=A;;
    12) n=B;;
    13) n=C;;
    14) n=D;;
    15) n=E;;
    16) n=F;;
    *)  n=$((i - 1));;
    esac
    print -r 'print "\e]P'${n}${colours[i]}'" > $tty'
  done
  echo "done"
} >~/.cache/ttycol.sh
chmod a+x ~/.cache/ttycol.sh
sudo mv ~/.cache/ttycol.sh /usr/local/bin/
sudo cp ~/.local/share/dots/ttycol.service /etc/systemd/system/
sudo systemctl enable ttycol.service
sudo systemctl start ttycol.service
