#!/bin/sh
while read -r file; do
	case "$1" in
	'w') setbg "$file" &;;
	'g') gimp "$file" &;;
	'c')
		destdir="$(menu -p "Copy $file to" <&- | sed "s|~|$HOME|")"
		[ "$destdir" ] || exit
		cp "$file" "$destdir" && notify-send "image copied to $destdir" &;;
	'm')
		destdir="$(menu -p "Move $file to" <&- | sed "s|~|$HOME|g")"
		[ "$destdir" ] || exit
		mv "$file" "$destdir" && notify-send "image moved to $destdir" &;;
	'd')
		prompt "Delete $file" && rm "$file" && notify-send "$file deleted" &;;
	'y')
		printf %s "$file" | xclip -selection clipboard &&
		notify-send "patch to image copied to clipboard" &;;
	'Y')
		xclip -selection clipboard -t image/png -i "$file" &&
		notify-send -i "$file" "image copied to clipboard" &;;
	esac
done
