#!/bin/sh
#  ██
# ░██              ██████
# ░██       ██████░██░░░██ ███     ██ ██████████
# ░██████  ██░░░░ ░██  ░██░░██  █ ░██░░██░░██░░██
# ░██░░░██░░█████ ░██████  ░██ ███░██ ░██ ░██ ░██
# ░██  ░██ ░░░░░██░██░░░   ░████░████ ░██ ░██ ░██
# ░██████  ██████ ░██      ███░ ░░░██ ███ ░██ ░██
# ░░░░░   ░░░░░░  ░░      ░░░    ░░░ ░░░  ░░  ░░

#===========
# Autostart
#===========
notify-send -i ~/.local/share/dots/arch.png "Welcome $(whoami)!" &
qutebrowser &
discord &
telegram-desktop &
#$TERMINAL -name scratchpad -e scratch &
mkdir -p ~/.config/bspwm/log

#===============
# Configuration
#===============
#bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor -d 0000 0001 0010 0011 0100 0101 0111 1000 1100 #1010
#bspc monitor LVDS1 -d 1 2 3 4 5 6 7 8 9
#bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9

# Mouse setings
bspc config pointer_modifier mod4
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_action3 resize_side
bspc config pointer_action2 resize_corner
bspc config pointer_action1 move

# Pading
#bspc config right_padding 5
#bspc config left_padding 5
#bspc config bottom_padding 5
#bspc config top_padding 15
bspc config right_monocle_padding 0
bspc config left_monocle_padding 0
bspc config bottom_monocle_padding 0
bspc config top_monocle_padding 0

# Gaps && Border
autogap &
cleanfullscreen &
#2bspwm &

bspc config border_width 0
#bspc config window_gap 10

# Disable border when is only one window
#bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Automatic scheme
bspc config automatic_scheme spiral
bspc config initial_polarity first_child
bspc config split_ratio          0.52

# Colorscheme
bg=$(xrdb -query | awk '/\*.background/ { printf $2 }')
bspc config normal_border_color "$bg"
bspc config focused_border_color "$bg"
bspc config presel_feedback_color "$bg"

#======
# Rule
#======
bspc desktop ^3 --layout next
bspc desktop ^4 --layout next
bspc rule -a firefox desktop='^3'
bspc rule -a qutebrowser desktop='^3'
bspc rule -a discord desktop='^4'
bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a Steam desktop='^8'
bspc rule -a network-manager state=floating sticky=on
bspc rule -a *::scratchpad sticky=on state=floating hidden=on locked=on
bspc rule -a lock sticky=on state=floating locked=on
bspc rule -a Zathura state=tiled
bspc rule -a *::float state=floating
bspc rule -a *::tiled state=tiled
